version: '3.1'

services:

  db:
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: universidadeweb
    volumes:
      - 'universidadeweb-db:/var/lib/mysql'

volumes:
  universidadeweb-db:
    driver: local
